# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import addition_pb2 as addition__pb2


class AdderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/addition.Adder/Add',
        request_serializer=addition__pb2.AddRequest.SerializeToString,
        response_deserializer=addition__pb2.AddReply.FromString,
        )


class AdderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=addition__pb2.AddRequest.FromString,
          response_serializer=addition__pb2.AddReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'addition.Adder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
